spring.application.name=topic1_1a

# MongoDB Atlas Database Connection Properties
server.port=8082
spring.mongodb.uri=mongodb+srv://hect183_db_user:K2y74tT2c5bvJPRV@cluster1.i7yeyhv.mongodb.net/cst339-order?retryWrites=true&w=majority&appName=Cluster1